version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379
  
volumes:
  redis:
    driver: local