version: '3.8'
services:
  redis:
    image: redis:6.2.5-alpine
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "300:3000"
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis:
    driver: local